    variable "env"{}
    variable "tags"{}
    variable "default_vpc_cidr"{}
    variable "default_vpc_id"{}
    variable "default_route_table_id"{}
    variable "account_id"{}
    variable "vpc"{}
    variable "route53_zone_id"{}
    variable "kms"{}
    variable "certificate_arn"{}
    variable "rds"{}
    variable "docdb"{}
    variable "elasticache"{}             
    variable "rabbitmq"{} 
    variable "bastion_cidrs"{} 
    variable "prometheus_cidrs"{} 
    variable "app"{}
